/* ============================================
   Level Data - 50 Levels (Auto-generated by grid-gen.js)
   ============================================ */

const LEVELS = [
  {
    "level": 1,
    "letters": [
      "C",
      "A",
      "T"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "CAT",
          "cellIds": [
            "c1",
            "a1",
            "t1"
          ],
          "phonetic": "/kæt/",
          "meaning": "n. 猫",
          "example": "The cat sleeps on the sofa.",
          "exampleCn": "猫在沙发上睡觉。"
        },
        {
          "word": "ACT",
          "cellIds": [
            "a2",
            "c1",
            "t2"
          ],
          "phonetic": "/ækt/",
          "meaning": "v. 行动；表演",
          "example": "We must act quickly.",
          "exampleCn": "我们必须迅速行动。"
        }
      ]
    }
  },
  {
    "level": 2,
    "letters": [
      "S",
      "T",
      "A",
      "R"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 1,
          "col": 2,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "R",
          "id": "r2"
        }
      ],
      "words": [
        {
          "word": "STAR",
          "cellIds": [
            "s1",
            "t1",
            "a1",
            "r1"
          ],
          "phonetic": "/stɑːr/",
          "meaning": "n. 星星；明星",
          "example": "Look at the bright star in the sky.",
          "exampleCn": "看天上那颗明亮的星星。"
        },
        {
          "word": "ART",
          "cellIds": [
            "a2",
            "r2",
            "t1"
          ],
          "phonetic": "/ɑːt/",
          "meaning": "n. 艺术",
          "example": "She studies art at college.",
          "exampleCn": "她在大学学习艺术。"
        }
      ]
    }
  },
  {
    "level": 3,
    "letters": [
      "R",
      "O",
      "S",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "O",
          "id": "o2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "S",
          "id": "s2"
        }
      ],
      "words": [
        {
          "word": "ROSE",
          "cellIds": [
            "r1",
            "o1",
            "s1",
            "e1"
          ],
          "phonetic": "/rəʊz/",
          "meaning": "n. 玫瑰；v. rise 的过去式",
          "example": "He gave her a red rose.",
          "exampleCn": "他送给她一朵红玫瑰。"
        },
        {
          "word": "ORES",
          "cellIds": [
            "o2",
            "r1",
            "e2",
            "s2"
          ],
          "phonetic": "/ɔːrz/",
          "meaning": "n. 矿石（复数）",
          "example": "The mine produces iron ores.",
          "exampleCn": "这座矿出产铁矿石。"
        }
      ]
    }
  },
  {
    "level": 4,
    "letters": [
      "L",
      "I",
      "S",
      "T"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "L",
          "id": "l1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "S",
          "id": "s2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "T",
          "id": "t2"
        },
        {
          "row": 1,
          "col": 2,
          "letter": "S",
          "id": "s3"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "L",
          "id": "l2"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "T",
          "id": "t3"
        }
      ],
      "words": [
        {
          "word": "LIST",
          "cellIds": [
            "l1",
            "i1",
            "s1",
            "t1"
          ],
          "phonetic": "/lɪst/",
          "meaning": "n. 列表；v. 列出",
          "example": "Make a list of things to buy.",
          "exampleCn": "列一张购物清单。"
        },
        {
          "word": "SILT",
          "cellIds": [
            "s2",
            "i2",
            "l1",
            "t2"
          ],
          "phonetic": "/sɪlt/",
          "meaning": "n. 淤泥",
          "example": "The river is full of silt.",
          "exampleCn": "这条河满是淤泥。"
        },
        {
          "word": "SLIT",
          "cellIds": [
            "s3",
            "l2",
            "i1",
            "t3"
          ],
          "phonetic": "/slɪt/",
          "meaning": "n. 裂缝；v. 切开",
          "example": "There is a slit in the curtain.",
          "exampleCn": "窗帘上有一道裂缝。"
        }
      ]
    }
  },
  {
    "level": 5,
    "letters": [
      "F",
      "I",
      "R",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "F",
          "id": "f1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "E",
          "id": "e2"
        }
      ],
      "words": [
        {
          "word": "FIRE",
          "cellIds": [
            "f1",
            "i1",
            "r1",
            "e1"
          ],
          "phonetic": "/ˈfaɪər/",
          "meaning": "n. 火；v. 解雇",
          "example": "The fire spread quickly.",
          "exampleCn": "火势蔓延得很快。"
        },
        {
          "word": "RIFE",
          "cellIds": [
            "r2",
            "i2",
            "f1",
            "e2"
          ],
          "phonetic": "/raɪf/",
          "meaning": "adj. 流行的，普遍的",
          "example": "Corruption is rife in the system.",
          "exampleCn": "腐败在这个系统中很普遍。"
        }
      ]
    }
  },
  {
    "level": 6,
    "letters": [
      "R",
      "O",
      "A",
      "D"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "O",
          "id": "o2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "D",
          "id": "d2"
        }
      ],
      "words": [
        {
          "word": "ROAD",
          "cellIds": [
            "r1",
            "o1",
            "a1",
            "d1"
          ],
          "phonetic": "/rəʊd/",
          "meaning": "n. 道路",
          "example": "The road is under repair.",
          "exampleCn": "这条路正在维修。"
        },
        {
          "word": "ORAD",
          "cellIds": [
            "o2",
            "r1",
            "a2",
            "d2"
          ],
          "phonetic": "/ˈɔːræd/",
          "meaning": "adv. 向口部",
          "example": "An orad movement.",
          "exampleCn": "向口部的运动。"
        }
      ]
    }
  },
  {
    "level": 7,
    "letters": [
      "T",
      "I",
      "M",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "M",
          "id": "m1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 0,
          "col": 1,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "M",
          "id": "m2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "E",
          "id": "e3"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "M",
          "id": "m3"
        }
      ],
      "words": [
        {
          "word": "TIME",
          "cellIds": [
            "t1",
            "i1",
            "m1",
            "e1"
          ],
          "phonetic": "/taɪm/",
          "meaning": "n. 时间",
          "example": "Time flies when you are having fun.",
          "exampleCn": "开心的时候时间飞逝。"
        },
        {
          "word": "EMIT",
          "cellIds": [
            "e2",
            "m2",
            "i2",
            "t1"
          ],
          "phonetic": "/ɪˈmɪt/",
          "meaning": "v. 发出，排放",
          "example": "The factory emits toxic gas.",
          "exampleCn": "这家工厂排放有毒气体。"
        },
        {
          "word": "ITEM",
          "cellIds": [
            "i2",
            "t1",
            "e3",
            "m3"
          ],
          "phonetic": "/ˈaɪtəm/",
          "meaning": "n. 项目，物品",
          "example": "This item is out of stock.",
          "exampleCn": "这件商品缺货。"
        }
      ]
    }
  },
  {
    "level": 8,
    "letters": [
      "P",
      "A",
      "L",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "P",
          "id": "p1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "L",
          "id": "l1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 0,
          "col": 1,
          "letter": "L",
          "id": "l2"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "A",
          "id": "a2"
        }
      ],
      "words": [
        {
          "word": "PALE",
          "cellIds": [
            "p1",
            "a1",
            "l1",
            "e1"
          ],
          "phonetic": "/peɪl/",
          "meaning": "adj. 苍白的",
          "example": "She looked pale and tired.",
          "exampleCn": "她看起来苍白而疲惫。"
        },
        {
          "word": "LEAP",
          "cellIds": [
            "l2",
            "e2",
            "a2",
            "p1"
          ],
          "phonetic": "/liːp/",
          "meaning": "v. 跳跃",
          "example": "The cat made a leap over the fence.",
          "exampleCn": "猫跳过围栏。"
        }
      ]
    }
  },
  {
    "level": 9,
    "letters": [
      "L",
      "A",
      "N",
      "D"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "L",
          "id": "l1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 0,
          "col": 1,
          "letter": "D",
          "id": "d2"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "A",
          "id": "a2"
        }
      ],
      "words": [
        {
          "word": "LAND",
          "cellIds": [
            "l1",
            "a1",
            "n1",
            "d1"
          ],
          "phonetic": "/lænd/",
          "meaning": "n. 土地；v. 着陆",
          "example": "The plane will land soon.",
          "exampleCn": "飞机即将着陆。"
        },
        {
          "word": "DUAL",
          "cellIds": [
            "d2",
            "u1",
            "a2",
            "l1"
          ],
          "phonetic": "/ˈdjuːəl/",
          "meaning": "adj. 双重的",
          "example": "The phone has dual cameras.",
          "exampleCn": "这款手机有双摄像头。"
        }
      ]
    }
  },
  {
    "level": 10,
    "letters": [
      "D",
      "U",
      "S",
      "T"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 0,
          "col": 1,
          "letter": "S",
          "id": "s2"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "T",
          "id": "t2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "U",
          "id": "u2"
        }
      ],
      "words": [
        {
          "word": "DUST",
          "cellIds": [
            "d1",
            "u1",
            "s1",
            "t1"
          ],
          "phonetic": "/dʌst/",
          "meaning": "n. 灰尘",
          "example": "The shelf is covered with dust.",
          "exampleCn": "架子上布满灰尘。"
        },
        {
          "word": "STUD",
          "cellIds": [
            "s2",
            "t2",
            "u2",
            "d1"
          ],
          "phonetic": "/stʌd/",
          "meaning": "n. 种马；耳钉",
          "example": "He wore diamond studs.",
          "exampleCn": "他戴着钻石耳钉。"
        }
      ]
    }
  },
  {
    "level": 11,
    "letters": [
      "R",
      "A",
      "T",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 0,
          "col": 1,
          "letter": "T",
          "id": "t2"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "A",
          "id": "a2"
        }
      ],
      "words": [
        {
          "word": "RATE",
          "cellIds": [
            "r1",
            "a1",
            "t1",
            "e1"
          ],
          "phonetic": "/reɪt/",
          "meaning": "n. 比率；v. 评价",
          "example": "The exchange rate is rising.",
          "exampleCn": "汇率正在上涨。"
        },
        {
          "word": "TEAR",
          "cellIds": [
            "t2",
            "e2",
            "a2",
            "r1"
          ],
          "phonetic": "/tɪər/",
          "meaning": "n. 眼泪；v. 撕裂",
          "example": "A tear rolled down her cheek.",
          "exampleCn": "一滴眼泪从她脸颊滑落。"
        }
      ]
    }
  },
  {
    "level": 12,
    "letters": [
      "B",
      "R",
      "E",
      "A",
      "D"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "B",
          "id": "b1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "D",
          "id": "d2"
        },
        {
          "row": 1,
          "col": 2,
          "letter": "D",
          "id": "d3"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "A",
          "id": "a3"
        }
      ],
      "words": [
        {
          "word": "BREAD",
          "cellIds": [
            "b1",
            "r1",
            "e1",
            "a1",
            "d1"
          ],
          "phonetic": "/bred/",
          "meaning": "n. 面包",
          "example": "Fresh bread smells wonderful.",
          "exampleCn": "新鲜面包闻起来很香。"
        },
        {
          "word": "READ",
          "cellIds": [
            "r1",
            "e2",
            "a2",
            "d2"
          ],
          "phonetic": "/riːd/",
          "meaning": "v. 阅读",
          "example": "I read a book every week.",
          "exampleCn": "我每周读一本书。"
        },
        {
          "word": "DARE",
          "cellIds": [
            "d3",
            "a3",
            "r1",
            "e2"
          ],
          "phonetic": "/deər/",
          "meaning": "v. 敢于",
          "example": "Do you dare to try?",
          "exampleCn": "你敢试试吗？"
        }
      ]
    }
  },
  {
    "level": 13,
    "letters": [
      "C",
      "L",
      "O",
      "U",
      "D"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "L",
          "id": "l1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "O",
          "id": "o2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "U",
          "id": "u2"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "D",
          "id": "d2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "O",
          "id": "o3"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "L",
          "id": "l2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "D",
          "id": "d3"
        }
      ],
      "words": [
        {
          "word": "CLOUD",
          "cellIds": [
            "c1",
            "l1",
            "o1",
            "u1",
            "d1"
          ],
          "phonetic": "/klaʊd/",
          "meaning": "n. 云",
          "example": "Dark clouds gathered overhead.",
          "exampleCn": "乌云在头顶聚集。"
        },
        {
          "word": "LOUD",
          "cellIds": [
            "l1",
            "o2",
            "u2",
            "d2"
          ],
          "phonetic": "/laʊd/",
          "meaning": "adj. 大声的",
          "example": "The music is too loud.",
          "exampleCn": "音乐太吵了。"
        },
        {
          "word": "COLD",
          "cellIds": [
            "c1",
            "o3",
            "l2",
            "d3"
          ],
          "phonetic": "/kəʊld/",
          "meaning": "adj. 冷的；n. 感冒",
          "example": "It is cold outside today.",
          "exampleCn": "今天外面很冷。"
        }
      ]
    }
  },
  {
    "level": 14,
    "letters": [
      "G",
      "R",
      "E",
      "E",
      "N"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "G",
          "id": "g1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "E",
          "id": "e3"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "N",
          "id": "n2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 7,
          "col": 1,
          "letter": "E",
          "id": "e4"
        }
      ],
      "words": [
        {
          "word": "GREEN",
          "cellIds": [
            "g1",
            "r1",
            "e1",
            "e2",
            "n1"
          ],
          "phonetic": "/ɡriːn/",
          "meaning": "adj. 绿色的",
          "example": "The grass is green.",
          "exampleCn": "草是绿色的。"
        },
        {
          "word": "GENRE",
          "cellIds": [
            "g1",
            "e3",
            "n2",
            "r2",
            "e4"
          ],
          "phonetic": "/ˈʒɒnrə/",
          "meaning": "n. 类型，体裁",
          "example": "What is your favorite music genre?",
          "exampleCn": "你最喜欢的音乐类型是什么？"
        }
      ]
    }
  },
  {
    "level": 15,
    "letters": [
      "F",
      "I",
      "E",
      "L",
      "D"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "F",
          "id": "f1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "L",
          "id": "l1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "L",
          "id": "l2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 7,
          "col": 1,
          "letter": "D",
          "id": "d2"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "D",
          "id": "d3"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "L",
          "id": "l3"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "E",
          "id": "e3"
        }
      ],
      "words": [
        {
          "word": "FIELD",
          "cellIds": [
            "f1",
            "i1",
            "e1",
            "l1",
            "d1"
          ],
          "phonetic": "/fiːld/",
          "meaning": "n. 田野；领域",
          "example": "She works in the medical field.",
          "exampleCn": "她在医学领域工作。"
        },
        {
          "word": "FILED",
          "cellIds": [
            "f1",
            "i2",
            "l2",
            "e2",
            "d2"
          ],
          "phonetic": "/faɪld/",
          "meaning": "v. file 的过去式，提交",
          "example": "He filed a complaint.",
          "exampleCn": "他提交了一份投诉。"
        },
        {
          "word": "IDLE",
          "cellIds": [
            "i1",
            "d3",
            "l3",
            "e3"
          ],
          "phonetic": "/ˈaɪdl/",
          "meaning": "adj. 空闲的；懒散的",
          "example": "The factory machines sat idle.",
          "exampleCn": "工厂的机器闲置着。"
        }
      ]
    }
  },
  {
    "level": 16,
    "letters": [
      "O",
      "C",
      "E",
      "A",
      "N"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "C",
          "id": "c2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "N",
          "id": "n2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "N",
          "id": "n3"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "E",
          "id": "e3"
        }
      ],
      "words": [
        {
          "word": "OCEAN",
          "cellIds": [
            "o1",
            "c1",
            "e1",
            "a1",
            "n1"
          ],
          "phonetic": "/ˈəʊʃn/",
          "meaning": "n. 海洋",
          "example": "The ocean is vast and blue.",
          "exampleCn": "海洋广阔而湛蓝。"
        },
        {
          "word": "CONE",
          "cellIds": [
            "c2",
            "o1",
            "n2",
            "e2"
          ],
          "phonetic": "/kəʊn/",
          "meaning": "n. 圆锥；松果",
          "example": "An ice cream cone, please.",
          "exampleCn": "请给我一个冰淇淋甜筒。"
        },
        {
          "word": "CANE",
          "cellIds": [
            "c1",
            "a2",
            "n3",
            "e3"
          ],
          "phonetic": "/keɪn/",
          "meaning": "n. 手杖；甘蔗",
          "example": "The old man walks with a cane.",
          "exampleCn": "老人拄着手杖走路。"
        }
      ]
    }
  },
  {
    "level": 17,
    "letters": [
      "B",
      "R",
      "I",
      "G",
      "H",
      "T"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "B",
          "id": "b1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "G",
          "id": "g1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "H",
          "id": "h1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "G",
          "id": "g2"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "H",
          "id": "h2"
        },
        {
          "row": 7,
          "col": 2,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "BRIGHT",
          "cellIds": [
            "b1",
            "r1",
            "i1",
            "g1",
            "h1",
            "t1"
          ],
          "phonetic": "/braɪt/",
          "meaning": "adj. 明亮的",
          "example": "The sun is bright today.",
          "exampleCn": "今天阳光明媚。"
        },
        {
          "word": "RIGHT",
          "cellIds": [
            "r1",
            "i2",
            "g2",
            "h2",
            "t2"
          ],
          "phonetic": "/raɪt/",
          "meaning": "adj. 正确的；n. 右边",
          "example": "Turn right at the corner.",
          "exampleCn": "在拐角处右转。"
        }
      ]
    }
  },
  {
    "level": 18,
    "letters": [
      "S",
      "T",
      "R",
      "E",
      "A",
      "M"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "M",
          "id": "m1"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "M",
          "id": "m2"
        }
      ],
      "words": [
        {
          "word": "STREAM",
          "cellIds": [
            "s1",
            "t1",
            "r1",
            "e1",
            "a1",
            "m1"
          ],
          "phonetic": "/striːm/",
          "meaning": "n. 小溪；v. 流动",
          "example": "A small stream runs through the village.",
          "exampleCn": "一条小溪穿过村庄。"
        },
        {
          "word": "TEAM",
          "cellIds": [
            "t1",
            "e2",
            "a2",
            "m2"
          ],
          "phonetic": "/tiːm/",
          "meaning": "n. 团队",
          "example": "Our team won the match.",
          "exampleCn": "我们队赢了比赛。"
        }
      ]
    }
  },
  {
    "level": 19,
    "letters": [
      "Y",
      "E",
      "L",
      "L",
      "O",
      "W"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "Y",
          "id": "y1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "L",
          "id": "l1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "L",
          "id": "l2"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "W",
          "id": "w1"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "W",
          "id": "w2"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "L",
          "id": "l3"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "L",
          "id": "l4"
        }
      ],
      "words": [
        {
          "word": "YELLOW",
          "cellIds": [
            "y1",
            "e1",
            "l1",
            "l2",
            "o1",
            "w1"
          ],
          "phonetic": "/ˈjeləʊ/",
          "meaning": "adj. 黄色的",
          "example": "The leaves turn yellow in autumn.",
          "exampleCn": "秋天叶子变黄。"
        },
        {
          "word": "WELL",
          "cellIds": [
            "w2",
            "e1",
            "l3",
            "l4"
          ],
          "phonetic": "/wel/",
          "meaning": "adv. 好地；n. 井",
          "example": "She plays the piano very well.",
          "exampleCn": "她钢琴弹得很好。"
        }
      ]
    }
  },
  {
    "level": 20,
    "letters": [
      "S",
      "I",
      "L",
      "V",
      "E",
      "R"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "L",
          "id": "l1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "V",
          "id": "v1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "L",
          "id": "l2"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "V",
          "id": "v2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "R",
          "id": "r2"
        }
      ],
      "words": [
        {
          "word": "SILVER",
          "cellIds": [
            "s1",
            "i1",
            "l1",
            "v1",
            "e1",
            "r1"
          ],
          "phonetic": "/ˈsɪlvər/",
          "meaning": "n. 银；adj. 银色的",
          "example": "She wore a silver necklace.",
          "exampleCn": "她戴着一条银项链。"
        },
        {
          "word": "LIVER",
          "cellIds": [
            "l2",
            "i1",
            "v2",
            "e2",
            "r2"
          ],
          "phonetic": "/ˈlɪvər/",
          "meaning": "n. 肝脏",
          "example": "The liver filters blood.",
          "exampleCn": "肝脏过滤血液。"
        }
      ]
    }
  },
  {
    "level": 21,
    "letters": [
      "O",
      "R",
      "A",
      "N",
      "G",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "G",
          "id": "g1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "N",
          "id": "n2"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "G",
          "id": "g2"
        },
        {
          "row": 7,
          "col": 2,
          "letter": "E",
          "id": "e2"
        }
      ],
      "words": [
        {
          "word": "ORANGE",
          "cellIds": [
            "o1",
            "r1",
            "a1",
            "n1",
            "g1",
            "e1"
          ],
          "phonetic": "/ˈɒrɪndʒ/",
          "meaning": "n. 橙子；adj. 橙色的",
          "example": "I drink orange juice every morning.",
          "exampleCn": "我每天早上喝橙汁。"
        },
        {
          "word": "RANGE",
          "cellIds": [
            "r1",
            "a2",
            "n2",
            "g2",
            "e2"
          ],
          "phonetic": "/reɪndʒ/",
          "meaning": "n. 范围",
          "example": "The price range is wide.",
          "exampleCn": "价格范围很广。"
        }
      ]
    }
  },
  {
    "level": 22,
    "letters": [
      "D",
      "I",
      "A",
      "M",
      "O",
      "N",
      "D"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "M",
          "id": "m1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "D",
          "id": "d2"
        }
      ],
      "words": [
        {
          "word": "DIAMOND",
          "cellIds": [
            "d1",
            "i1",
            "a1",
            "m1",
            "o1",
            "n1",
            "d2"
          ],
          "phonetic": "/ˈdaɪəmənd/",
          "meaning": "n. 钻石",
          "example": "A diamond ring sparkled on her finger.",
          "exampleCn": "她手指上的钻戒闪闪发光。"
        }
      ]
    }
  },
  {
    "level": 23,
    "letters": [
      "S",
      "U",
      "N",
      "S",
      "E",
      "T"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "S",
          "id": "s2"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "N",
          "id": "n2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "SUNSET",
          "cellIds": [
            "s1",
            "u1",
            "n1",
            "s2",
            "e1",
            "t1"
          ],
          "phonetic": "/ˈsʌnset/",
          "meaning": "n. 日落",
          "example": "We watched the sunset at the beach.",
          "exampleCn": "我们在海滩看日落。"
        },
        {
          "word": "NEST",
          "cellIds": [
            "n2",
            "e2",
            "s1",
            "t2"
          ],
          "phonetic": "/nest/",
          "meaning": "n. 巢",
          "example": "The bird built a nest in the tree.",
          "exampleCn": "鸟在树上筑了一个巢。"
        }
      ]
    }
  },
  {
    "level": 24,
    "letters": [
      "W",
      "I",
      "N",
      "T",
      "E",
      "R"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "W",
          "id": "w1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "T",
          "id": "t2"
        },
        {
          "row": 7,
          "col": 1,
          "letter": "E",
          "id": "e2"
        }
      ],
      "words": [
        {
          "word": "WINTER",
          "cellIds": [
            "w1",
            "i1",
            "n1",
            "t1",
            "e1",
            "r1"
          ],
          "phonetic": "/ˈwɪntər/",
          "meaning": "n. 冬天",
          "example": "Winter is my favorite season.",
          "exampleCn": "冬天是我最喜欢的季节。"
        },
        {
          "word": "WRITE",
          "cellIds": [
            "w1",
            "r2",
            "i2",
            "t2",
            "e2"
          ],
          "phonetic": "/raɪt/",
          "meaning": "v. 写",
          "example": "I write in my diary every night.",
          "exampleCn": "我每晚写日记。"
        }
      ]
    }
  },
  {
    "level": 25,
    "letters": [
      "S",
      "U",
      "M",
      "M",
      "E",
      "R"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "M",
          "id": "m1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "M",
          "id": "m2"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "U",
          "id": "u2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "R",
          "id": "r2"
        }
      ],
      "words": [
        {
          "word": "SUMMER",
          "cellIds": [
            "s1",
            "u1",
            "m1",
            "m2",
            "e1",
            "r1"
          ],
          "phonetic": "/ˈsʌmər/",
          "meaning": "n. 夏天",
          "example": "We go swimming every summer.",
          "exampleCn": "我们每年夏天都去游泳。"
        },
        {
          "word": "USER",
          "cellIds": [
            "u2",
            "s1",
            "e2",
            "r2"
          ],
          "phonetic": "/ˈjuːzər/",
          "meaning": "n. 用户",
          "example": "The app has one million users.",
          "exampleCn": "这款应用有一百万用户。"
        }
      ]
    }
  },
  {
    "level": 26,
    "letters": [
      "S",
      "P",
      "R",
      "I",
      "N",
      "G"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "P",
          "id": "p1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "G",
          "id": "g1"
        },
        {
          "row": -1,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 0,
          "col": 1,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "N",
          "id": "n2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "G",
          "id": "g2"
        }
      ],
      "words": [
        {
          "word": "SPRING",
          "cellIds": [
            "s1",
            "p1",
            "r1",
            "i1",
            "n1",
            "g1"
          ],
          "phonetic": "/sprɪŋ/",
          "meaning": "n. 春天；弹簧",
          "example": "Spring is the season of growth.",
          "exampleCn": "春天是生长的季节。"
        },
        {
          "word": "RINGS",
          "cellIds": [
            "r2",
            "i2",
            "n2",
            "g2",
            "s1"
          ],
          "phonetic": "/rɪŋz/",
          "meaning": "n. 戒指（复数）；v. ring 的第三人称单数",
          "example": "She wears two gold rings.",
          "exampleCn": "她戴着两枚金戒指。"
        }
      ]
    }
  },
  {
    "level": 27,
    "letters": [
      "B",
      "R",
      "I",
      "D",
      "G",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "B",
          "id": "b1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "G",
          "id": "g1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "D",
          "id": "d2"
        }
      ],
      "words": [
        {
          "word": "BRIDGE",
          "cellIds": [
            "b1",
            "r1",
            "i1",
            "d1",
            "g1",
            "e1"
          ],
          "phonetic": "/brɪdʒ/",
          "meaning": "n. 桥",
          "example": "The bridge crosses the river.",
          "exampleCn": "这座桥横跨河流。"
        },
        {
          "word": "BIRD",
          "cellIds": [
            "b1",
            "i2",
            "r2",
            "d2"
          ],
          "phonetic": "/bɜːd/",
          "meaning": "n. 鸟",
          "example": "A bird sang in the tree.",
          "exampleCn": "一只鸟在树上唱歌。"
        }
      ]
    }
  },
  {
    "level": 28,
    "letters": [
      "V",
      "I",
      "L",
      "L",
      "A",
      "G",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "V",
          "id": "v1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "L",
          "id": "l1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "L",
          "id": "l2"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "G",
          "id": "g1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "G",
          "id": "g2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "E",
          "id": "e2"
        }
      ],
      "words": [
        {
          "word": "VILLAGE",
          "cellIds": [
            "v1",
            "i1",
            "l1",
            "l2",
            "a1",
            "g1",
            "e1"
          ],
          "phonetic": "/ˈvɪlɪdʒ/",
          "meaning": "n. 村庄",
          "example": "A small village by the lake.",
          "exampleCn": "湖边的一个小村庄。"
        },
        {
          "word": "GIVE",
          "cellIds": [
            "g2",
            "i2",
            "v1",
            "e2"
          ],
          "phonetic": "/ɡɪv/",
          "meaning": "v. 给",
          "example": "Give me a hand, please.",
          "exampleCn": "请帮我一下。"
        }
      ]
    }
  },
  {
    "level": 29,
    "letters": [
      "T",
      "H",
      "O",
      "U",
      "G",
      "H",
      "T"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "H",
          "id": "h1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "G",
          "id": "g1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "H",
          "id": "h2"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "T",
          "id": "t2"
        },
        {
          "row": -1,
          "col": 1,
          "letter": "O",
          "id": "o2"
        },
        {
          "row": 0,
          "col": 1,
          "letter": "U",
          "id": "u2"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "G",
          "id": "g2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "H",
          "id": "h3"
        }
      ],
      "words": [
        {
          "word": "THOUGHT",
          "cellIds": [
            "t1",
            "h1",
            "o1",
            "u1",
            "g1",
            "h2",
            "t2"
          ],
          "phonetic": "/θɔːt/",
          "meaning": "n. 想法",
          "example": "A thought crossed my mind.",
          "exampleCn": "一个想法掠过我的脑海。"
        },
        {
          "word": "OUGHT",
          "cellIds": [
            "o2",
            "u2",
            "g2",
            "h3",
            "t1"
          ],
          "phonetic": "/ɔːt/",
          "meaning": "aux. 应该",
          "example": "You ought to try harder.",
          "exampleCn": "你应该更努力。"
        }
      ]
    }
  },
  {
    "level": 30,
    "letters": [
      "P",
      "I",
      "C",
      "T",
      "U",
      "R",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "P",
          "id": "p1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "U",
          "id": "u2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "E",
          "id": "e2"
        }
      ],
      "words": [
        {
          "word": "PICTURE",
          "cellIds": [
            "p1",
            "i1",
            "c1",
            "t1",
            "u1",
            "r1",
            "e1"
          ],
          "phonetic": "/ˈpɪktʃər/",
          "meaning": "n. 图片，照片",
          "example": "Take a picture of the sunset.",
          "exampleCn": "拍一张日落的照片。"
        },
        {
          "word": "PURE",
          "cellIds": [
            "p1",
            "u2",
            "r2",
            "e2"
          ],
          "phonetic": "/pjʊər/",
          "meaning": "adj. 纯的",
          "example": "The water is pure and clean.",
          "exampleCn": "水纯净清澈。"
        }
      ]
    }
  },
  {
    "level": 31,
    "letters": [
      "C",
      "A",
      "P",
      "T",
      "A",
      "I",
      "N"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "P",
          "id": "p1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "P",
          "id": "p2"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "N",
          "id": "n2"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "CAPTAIN",
          "cellIds": [
            "c1",
            "a1",
            "p1",
            "t1",
            "a2",
            "i1",
            "n1"
          ],
          "phonetic": "/ˈkæptɪn/",
          "meaning": "n. 船长；队长",
          "example": "The captain steered the ship.",
          "exampleCn": "船长驾驶着船。"
        },
        {
          "word": "PAINT",
          "cellIds": [
            "p2",
            "a1",
            "i2",
            "n2",
            "t2"
          ],
          "phonetic": "/peɪnt/",
          "meaning": "n. 油漆；v. 绘画",
          "example": "She loves to paint landscapes.",
          "exampleCn": "她喜欢画风景画。"
        }
      ]
    }
  },
  {
    "level": 32,
    "letters": [
      "W",
      "E",
      "A",
      "T",
      "H",
      "E",
      "R"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "W",
          "id": "w1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "H",
          "id": "h1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "H",
          "id": "h2"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "WEATHER",
          "cellIds": [
            "w1",
            "e1",
            "a1",
            "t1",
            "h1",
            "e2",
            "r1"
          ],
          "phonetic": "/ˈweðər/",
          "meaning": "n. 天气",
          "example": "The weather is nice today.",
          "exampleCn": "今天天气很好。"
        },
        {
          "word": "HEAT",
          "cellIds": [
            "h2",
            "e1",
            "a2",
            "t2"
          ],
          "phonetic": "/hiːt/",
          "meaning": "n. 热",
          "example": "The heat is unbearable.",
          "exampleCn": "热得难以忍受。"
        }
      ]
    }
  },
  {
    "level": 33,
    "letters": [
      "F",
      "O",
      "R",
      "E",
      "S",
      "T",
      "S"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "F",
          "id": "f1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "S",
          "id": "s2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "O",
          "id": "o2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 7,
          "col": 1,
          "letter": "S",
          "id": "s3"
        },
        {
          "row": 8,
          "col": 1,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "FORESTS",
          "cellIds": [
            "f1",
            "o1",
            "r1",
            "e1",
            "s1",
            "t1",
            "s2"
          ],
          "phonetic": "/ˈfɒrɪsts/",
          "meaning": "n. 森林（复数）",
          "example": "Dense forests cover the mountain.",
          "exampleCn": "茂密的森林覆盖着山脉。"
        },
        {
          "word": "FOREST",
          "cellIds": [
            "f1",
            "o2",
            "r2",
            "e2",
            "s3",
            "t2"
          ],
          "phonetic": "/ˈfɒrɪst/",
          "meaning": "n. 森林",
          "example": "We camped in the forest.",
          "exampleCn": "我们在森林里露营。"
        }
      ]
    }
  },
  {
    "level": 34,
    "letters": [
      "G",
      "A",
      "R",
      "D",
      "E",
      "N",
      "S"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "G",
          "id": "g1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 1,
          "col": 2,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "D",
          "id": "d2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "S",
          "id": "s2"
        }
      ],
      "words": [
        {
          "word": "GARDENS",
          "cellIds": [
            "g1",
            "a1",
            "r1",
            "d1",
            "e1",
            "n1",
            "s1"
          ],
          "phonetic": "/ˈɡɑːdnz/",
          "meaning": "n. 花园（复数）",
          "example": "The palace has beautiful gardens.",
          "exampleCn": "这座宫殿有美丽的花园。"
        },
        {
          "word": "READS",
          "cellIds": [
            "r2",
            "e2",
            "a1",
            "d2",
            "s2"
          ],
          "phonetic": "/riːdz/",
          "meaning": "v. 阅读（第三人称单数）",
          "example": "She reads every night.",
          "exampleCn": "她每晚都阅读。"
        }
      ]
    }
  },
  {
    "level": 35,
    "letters": [
      "J",
      "O",
      "U",
      "R",
      "N",
      "E",
      "Y"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "J",
          "id": "j1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "Y",
          "id": "y1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "U",
          "id": "u2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "Y",
          "id": "y2"
        }
      ],
      "words": [
        {
          "word": "JOURNEY",
          "cellIds": [
            "j1",
            "o1",
            "u1",
            "r1",
            "n1",
            "e1",
            "y1"
          ],
          "phonetic": "/ˈdʒɜːni/",
          "meaning": "n. 旅程",
          "example": "Life is a journey, not a destination.",
          "exampleCn": "人生是一场旅程，不是终点。"
        },
        {
          "word": "JURY",
          "cellIds": [
            "j1",
            "u2",
            "r2",
            "y2"
          ],
          "phonetic": "/ˈdʒʊəri/",
          "meaning": "n. 陪审团",
          "example": "The jury reached a verdict.",
          "exampleCn": "陪审团做出了裁决。"
        }
      ]
    }
  },
  {
    "level": 36,
    "letters": [
      "C",
      "H",
      "A",
      "P",
      "T",
      "E",
      "R"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "H",
          "id": "h1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "P",
          "id": "p1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "H",
          "id": "h2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 7,
          "col": 1,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "CHAPTER",
          "cellIds": [
            "c1",
            "h1",
            "a1",
            "p1",
            "t1",
            "e1",
            "r1"
          ],
          "phonetic": "/ˈtʃæptər/",
          "meaning": "n. 章节",
          "example": "Read chapter three by Monday.",
          "exampleCn": "周一前读完第三章。"
        },
        {
          "word": "CHART",
          "cellIds": [
            "c1",
            "h2",
            "a2",
            "r2",
            "t2"
          ],
          "phonetic": "/tʃɑːt/",
          "meaning": "n. 图表",
          "example": "The chart shows sales growth.",
          "exampleCn": "图表显示了销售增长。"
        }
      ]
    }
  },
  {
    "level": 37,
    "letters": [
      "D",
      "E",
      "S",
      "T",
      "R",
      "O",
      "Y"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "Y",
          "id": "y1"
        },
        {
          "row": -1,
          "col": 2,
          "letter": "S",
          "id": "s2"
        },
        {
          "row": 0,
          "col": 2,
          "letter": "T",
          "id": "t2"
        },
        {
          "row": 1,
          "col": 2,
          "letter": "O",
          "id": "o2"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "R",
          "id": "r2"
        }
      ],
      "words": [
        {
          "word": "DESTROY",
          "cellIds": [
            "d1",
            "e1",
            "s1",
            "t1",
            "r1",
            "o1",
            "y1"
          ],
          "phonetic": "/dɪˈstrɔɪ/",
          "meaning": "v. 摧毁",
          "example": "The fire destroyed the house.",
          "exampleCn": "大火摧毁了房子。"
        },
        {
          "word": "STORE",
          "cellIds": [
            "s2",
            "t2",
            "o2",
            "r2",
            "e1"
          ],
          "phonetic": "/stɔːr/",
          "meaning": "n. 商店；v. 储存",
          "example": "I need to go to the store.",
          "exampleCn": "我需要去商店。"
        }
      ]
    }
  },
  {
    "level": 38,
    "letters": [
      "H",
      "I",
      "S",
      "T",
      "O",
      "R",
      "Y"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "H",
          "id": "h1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "Y",
          "id": "y1"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "S",
          "id": "s2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "O",
          "id": "o2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "HISTORY",
          "cellIds": [
            "h1",
            "i1",
            "s1",
            "t1",
            "o1",
            "r1",
            "y1"
          ],
          "phonetic": "/ˈhɪstri/",
          "meaning": "n. 历史",
          "example": "History repeats itself.",
          "exampleCn": "历史总是重演。"
        },
        {
          "word": "SHORT",
          "cellIds": [
            "s2",
            "h1",
            "o2",
            "r2",
            "t2"
          ],
          "phonetic": "/ʃɔːt/",
          "meaning": "adj. 短的",
          "example": "He is short but strong.",
          "exampleCn": "他个子矮但很强壮。"
        }
      ]
    }
  },
  {
    "level": 39,
    "letters": [
      "F",
      "A",
      "S",
      "H",
      "I",
      "O",
      "N"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "F",
          "id": "f1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "H",
          "id": "h1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "N",
          "id": "n2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "S",
          "id": "s2"
        }
      ],
      "words": [
        {
          "word": "FASHION",
          "cellIds": [
            "f1",
            "a1",
            "s1",
            "h1",
            "i1",
            "o1",
            "n1"
          ],
          "phonetic": "/ˈfæʃn/",
          "meaning": "n. 时尚",
          "example": "She works in the fashion industry.",
          "exampleCn": "她在时尚行业工作。"
        },
        {
          "word": "FANS",
          "cellIds": [
            "f1",
            "a2",
            "n2",
            "s2"
          ],
          "phonetic": "/fænz/",
          "meaning": "n. 粉丝（复数）",
          "example": "The singer has millions of fans.",
          "exampleCn": "这位歌手有数百万粉丝。"
        }
      ]
    }
  },
  {
    "level": 40,
    "letters": [
      "P",
      "R",
      "O",
      "B",
      "L",
      "E",
      "M"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "P",
          "id": "p1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "B",
          "id": "b1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "L",
          "id": "l1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "M",
          "id": "m1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "O",
          "id": "o2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "B",
          "id": "b2"
        },
        {
          "row": 7,
          "col": 1,
          "letter": "E",
          "id": "e2"
        }
      ],
      "words": [
        {
          "word": "PROBLEM",
          "cellIds": [
            "p1",
            "r1",
            "o1",
            "b1",
            "l1",
            "e1",
            "m1"
          ],
          "phonetic": "/ˈprɒbləm/",
          "meaning": "n. 问题",
          "example": "Every problem has a solution.",
          "exampleCn": "每个问题都有解决方案。"
        },
        {
          "word": "PROBE",
          "cellIds": [
            "p1",
            "r2",
            "o2",
            "b2",
            "e2"
          ],
          "phonetic": "/prəʊb/",
          "meaning": "n. 探测器；v. 探查",
          "example": "The doctor used a probe.",
          "exampleCn": "医生使用了探针。"
        }
      ]
    }
  },
  {
    "level": 41,
    "letters": [
      "T",
      "R",
      "E",
      "A",
      "S",
      "U",
      "R",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 3,
          "col": 8,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "S",
          "id": "s2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "R",
          "id": "r3"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "E",
          "id": "e3"
        }
      ],
      "words": [
        {
          "word": "TREASURE",
          "cellIds": [
            "t1",
            "r1",
            "e1",
            "a1",
            "s1",
            "u1",
            "r2",
            "e2"
          ],
          "phonetic": "/ˈtreʒər/",
          "meaning": "n. 宝藏",
          "example": "The pirates buried their treasure.",
          "exampleCn": "海盗埋藏了他们的宝藏。"
        },
        {
          "word": "STARE",
          "cellIds": [
            "s2",
            "t1",
            "a2",
            "r3",
            "e3"
          ],
          "phonetic": "/steər/",
          "meaning": "v. 凝视",
          "example": "Do not stare at strangers.",
          "exampleCn": "不要盯着陌生人看。"
        }
      ]
    }
  },
  {
    "level": 42,
    "letters": [
      "T",
      "E",
      "A",
      "C",
      "H",
      "E",
      "R",
      "S"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "H",
          "id": "h1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 8,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "E",
          "id": "e3"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "C",
          "id": "c2"
        },
        {
          "row": 7,
          "col": 1,
          "letter": "H",
          "id": "h2"
        },
        {
          "row": 8,
          "col": 1,
          "letter": "E",
          "id": "e4"
        },
        {
          "row": 9,
          "col": 1,
          "letter": "S",
          "id": "s2"
        }
      ],
      "words": [
        {
          "word": "TEACHERS",
          "cellIds": [
            "t1",
            "e1",
            "a1",
            "c1",
            "h1",
            "e2",
            "r1",
            "s1"
          ],
          "phonetic": "/ˈtiːtʃərz/",
          "meaning": "n. 老师（复数）",
          "example": "The teachers are in the meeting room.",
          "exampleCn": "老师们正在会议室里。"
        },
        {
          "word": "TEACHES",
          "cellIds": [
            "t1",
            "e3",
            "a2",
            "c2",
            "h2",
            "e4",
            "s2"
          ],
          "phonetic": "/ˈtiːtʃɪz/",
          "meaning": "v. 教（第三人称单数）",
          "example": "She teaches English at school.",
          "exampleCn": "她在学校教英语。"
        }
      ]
    }
  },
  {
    "level": 43,
    "letters": [
      "Q",
      "U",
      "E",
      "S",
      "T",
      "I",
      "O",
      "N"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "Q",
          "id": "q1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 8,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "U",
          "id": "u2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "S",
          "id": "s2"
        },
        {
          "row": 7,
          "col": 1,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "QUESTION",
          "cellIds": [
            "q1",
            "u1",
            "e1",
            "s1",
            "t1",
            "i1",
            "o1",
            "n1"
          ],
          "phonetic": "",
          "meaning": "n. question",
          "example": "Example sentence with question.",
          "exampleCn": "包含 question 的例句。"
        },
        {
          "word": "QUEST",
          "cellIds": [
            "q1",
            "u2",
            "e2",
            "s2",
            "t2"
          ],
          "phonetic": "/kwest/",
          "meaning": "n. 探索，追求",
          "example": "He went on a quest for knowledge.",
          "exampleCn": "他踏上了求知之旅。"
        }
      ]
    }
  },
  {
    "level": 44,
    "letters": [
      "P",
      "O",
      "S",
      "I",
      "T",
      "I",
      "V",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "P",
          "id": "p1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "I",
          "id": "i2"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "V",
          "id": "v1"
        },
        {
          "row": 3,
          "col": 8,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 1,
          "col": 3,
          "letter": "V",
          "id": "v2"
        },
        {
          "row": 2,
          "col": 3,
          "letter": "I",
          "id": "i3"
        },
        {
          "row": 4,
          "col": 3,
          "letter": "I",
          "id": "i4"
        },
        {
          "row": 5,
          "col": 3,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "POSITIVE",
          "cellIds": [
            "p1",
            "o1",
            "s1",
            "i1",
            "t1",
            "i2",
            "v1",
            "e1"
          ],
          "phonetic": "",
          "meaning": "n. positive",
          "example": "Example sentence with positive.",
          "exampleCn": "包含 positive 的例句。"
        },
        {
          "word": "VISIT",
          "cellIds": [
            "v2",
            "i3",
            "s1",
            "i4",
            "t2"
          ],
          "phonetic": "",
          "meaning": "n. visit",
          "example": "Example sentence with visit.",
          "exampleCn": "包含 visit 的例句。"
        }
      ]
    }
  },
  {
    "level": 45,
    "letters": [
      "C",
      "O",
      "M",
      "P",
      "L",
      "E",
      "T",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "M",
          "id": "m1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "P",
          "id": "p1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "L",
          "id": "l1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 8,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "P",
          "id": "p2"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "E",
          "id": "e3"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "T",
          "id": "t2"
        }
      ],
      "words": [
        {
          "word": "COMPLETE",
          "cellIds": [
            "c1",
            "o1",
            "m1",
            "p1",
            "l1",
            "e1",
            "t1",
            "e2"
          ],
          "phonetic": "",
          "meaning": "n. complete",
          "example": "Example sentence with complete.",
          "exampleCn": "包含 complete 的例句。"
        },
        {
          "word": "POET",
          "cellIds": [
            "p2",
            "o1",
            "e3",
            "t2"
          ],
          "phonetic": "/ˈpəʊɪt/",
          "meaning": "n. 诗人",
          "example": "The poet wrote beautiful verses.",
          "exampleCn": "这位诗人写下了优美的诗句。"
        }
      ]
    }
  },
  {
    "level": 46,
    "letters": [
      "P",
      "R",
      "A",
      "C",
      "T",
      "I",
      "C",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "P",
          "id": "p1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "C",
          "id": "c2"
        },
        {
          "row": 3,
          "col": 8,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "T",
          "id": "t2"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "C",
          "id": "c3"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "E",
          "id": "e2"
        }
      ],
      "words": [
        {
          "word": "PRACTICE",
          "cellIds": [
            "p1",
            "r1",
            "a1",
            "c1",
            "t1",
            "i1",
            "c2",
            "e1"
          ],
          "phonetic": "",
          "meaning": "n. practice",
          "example": "Example sentence with practice.",
          "exampleCn": "包含 practice 的例句。"
        },
        {
          "word": "TRACE",
          "cellIds": [
            "t2",
            "r1",
            "a2",
            "c3",
            "e2"
          ],
          "phonetic": "",
          "meaning": "n. trace",
          "example": "Example sentence with trace.",
          "exampleCn": "包含 trace 的例句。"
        }
      ]
    }
  },
  {
    "level": 47,
    "letters": [
      "I",
      "N",
      "T",
      "E",
      "R",
      "E",
      "S",
      "T"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 8,
          "letter": "T",
          "id": "t2"
        },
        {
          "row": 2,
          "col": 2,
          "letter": "E",
          "id": "e3"
        },
        {
          "row": 4,
          "col": 2,
          "letter": "T",
          "id": "t3"
        },
        {
          "row": 5,
          "col": 2,
          "letter": "E",
          "id": "e4"
        },
        {
          "row": 6,
          "col": 2,
          "letter": "R",
          "id": "r2"
        }
      ],
      "words": [
        {
          "word": "INTEREST",
          "cellIds": [
            "i1",
            "n1",
            "t1",
            "e1",
            "r1",
            "e2",
            "s1",
            "t2"
          ],
          "phonetic": "",
          "meaning": "n. interest",
          "example": "Example sentence with interest.",
          "exampleCn": "包含 interest 的例句。"
        },
        {
          "word": "ENTER",
          "cellIds": [
            "e3",
            "n1",
            "t3",
            "e4",
            "r2"
          ],
          "phonetic": "/ˈentər/",
          "meaning": "v. 进入",
          "example": "Please enter through the front door.",
          "exampleCn": "请从前门进入。"
        }
      ]
    }
  },
  {
    "level": 48,
    "letters": [
      "R",
      "E",
      "S",
      "E",
      "A",
      "R",
      "C",
      "H"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "S",
          "id": "s1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 8,
          "letter": "H",
          "id": "h1"
        },
        {
          "row": 0,
          "col": 1,
          "letter": "S",
          "id": "s2"
        },
        {
          "row": 1,
          "col": 1,
          "letter": "E",
          "id": "e3"
        },
        {
          "row": 2,
          "col": 1,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "C",
          "id": "c2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "H",
          "id": "h2"
        }
      ],
      "words": [
        {
          "word": "RESEARCH",
          "cellIds": [
            "r1",
            "e1",
            "s1",
            "e2",
            "a1",
            "r2",
            "c1",
            "h1"
          ],
          "phonetic": "",
          "meaning": "n. research",
          "example": "Example sentence with research.",
          "exampleCn": "包含 research 的例句。"
        },
        {
          "word": "SEARCH",
          "cellIds": [
            "s2",
            "e3",
            "a2",
            "r1",
            "c2",
            "h2"
          ],
          "phonetic": "",
          "meaning": "n. search",
          "example": "Example sentence with search.",
          "exampleCn": "包含 search 的例句。"
        }
      ]
    }
  },
  {
    "level": 49,
    "letters": [
      "C",
      "H",
      "A",
      "M",
      "P",
      "I",
      "O",
      "N"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "C",
          "id": "c1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "H",
          "id": "h1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "M",
          "id": "m1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "P",
          "id": "p1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "I",
          "id": "i1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "O",
          "id": "o1"
        },
        {
          "row": 3,
          "col": 8,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 4,
          "col": 1,
          "letter": "H",
          "id": "h2"
        },
        {
          "row": 5,
          "col": 1,
          "letter": "A",
          "id": "a2"
        },
        {
          "row": 6,
          "col": 1,
          "letter": "M",
          "id": "m2"
        },
        {
          "row": 7,
          "col": 1,
          "letter": "P",
          "id": "p2"
        }
      ],
      "words": [
        {
          "word": "CHAMPION",
          "cellIds": [
            "c1",
            "h1",
            "a1",
            "m1",
            "p1",
            "i1",
            "o1",
            "n1"
          ],
          "phonetic": "",
          "meaning": "n. champion",
          "example": "Example sentence with champion.",
          "exampleCn": "包含 champion 的例句。"
        },
        {
          "word": "CHAMP",
          "cellIds": [
            "c1",
            "h2",
            "a2",
            "m2",
            "p2"
          ],
          "phonetic": "/tʃæmp/",
          "meaning": "n. 冠军（口语）",
          "example": "He is the champ of the tournament.",
          "exampleCn": "他是锦标赛的冠军。"
        }
      ]
    }
  },
  {
    "level": 50,
    "letters": [
      "A",
      "D",
      "V",
      "E",
      "N",
      "T",
      "U",
      "R",
      "E"
    ],
    "grid": {
      "cells": [
        {
          "row": 3,
          "col": 1,
          "letter": "A",
          "id": "a1"
        },
        {
          "row": 3,
          "col": 2,
          "letter": "D",
          "id": "d1"
        },
        {
          "row": 3,
          "col": 3,
          "letter": "V",
          "id": "v1"
        },
        {
          "row": 3,
          "col": 4,
          "letter": "E",
          "id": "e1"
        },
        {
          "row": 3,
          "col": 5,
          "letter": "N",
          "id": "n1"
        },
        {
          "row": 3,
          "col": 6,
          "letter": "T",
          "id": "t1"
        },
        {
          "row": 3,
          "col": 7,
          "letter": "U",
          "id": "u1"
        },
        {
          "row": 3,
          "col": 8,
          "letter": "R",
          "id": "r1"
        },
        {
          "row": 3,
          "col": 9,
          "letter": "E",
          "id": "e2"
        },
        {
          "row": 4,
          "col": 3,
          "letter": "E",
          "id": "e3"
        },
        {
          "row": 5,
          "col": 3,
          "letter": "N",
          "id": "n2"
        },
        {
          "row": 6,
          "col": 3,
          "letter": "T",
          "id": "t2"
        },
        {
          "row": 7,
          "col": 3,
          "letter": "U",
          "id": "u2"
        },
        {
          "row": 8,
          "col": 3,
          "letter": "R",
          "id": "r2"
        },
        {
          "row": 9,
          "col": 3,
          "letter": "E",
          "id": "e4"
        }
      ],
      "words": [
        {
          "word": "ADVENTURE",
          "cellIds": [
            "a1",
            "d1",
            "v1",
            "e1",
            "n1",
            "t1",
            "u1",
            "r1",
            "e2"
          ],
          "phonetic": "",
          "meaning": "n. adventure",
          "example": "Example sentence with adventure.",
          "exampleCn": "包含 adventure 的例句。"
        },
        {
          "word": "VENTURE",
          "cellIds": [
            "v1",
            "e3",
            "n2",
            "t2",
            "u2",
            "r2",
            "e4"
          ],
          "phonetic": "/ˈventʃər/",
          "meaning": "n. 冒险；v. 敢于",
          "example": "The business venture was risky.",
          "exampleCn": "这项商业投资有风险。"
        }
      ]
    }
  }
];
